### ISSUE TITLE
how about speed?

### ISSUE THREAD

**Issue by Mrils** [FangGet/PackNet-SFM-PyTorch#1]
Hello:
    Thanks for your excellent work! 
    But I am curious how much frame rate the model can reach after reducing the amount of parameters?

**Comment by FangGet** [comment]
Parameter reduce in this project is not for speed purpose.  I will test it later and give the framerate for you.

**Comment by FangGet** [comment]
@Mrils I just had a test for only depth estimation part on both CPU and GPU, here are the results:
for GPU (RTX 2060), it's on average 10ms per input frame (640 * 192)
for CPU (i7-8700 3.2GHz), it;s on average 30s per input frame (640*192)

Hope it helps.

**Comment by Mrils** [comment]
thx!
