### ISSUE TITLE
would you provide an improved version corresponding to the original paper?

### ISSUE THREAD

**Issue by TengFeiHan0** [FangGet/PackNet-SFM-PyTorch#3]

**Comment by FangGet** [comment]
Sorry for late reply, I'm working for a paper with an improved version of packnet along with some new ideas, as is on the way, so code are not avariable currently.

**Comment by TengFeiHan0** [comment]
> Sorry for late reply, I'm working for a paper with an improved version of packnet along with some new ideas, as is on the way, so code are not avariable currently.

@FangGet  which paper do you refer to? do you mean "SEMANTICALLY-GUIDED REPRESENTATION LEARN- ING FOR SELF-SUPERVISED MONOCULAR DEPTH"? it is a paper produced by the same author and published on ICLR2020, which uses a fixed semantic segmentation network to guide our depth prediction module. 

Actually, I already reproduced this paper. my results(**monodepth2-based** not packnet) are a little better than the author's due to the difference of semantically-guided network. if you also are interested in this paper, I'm glad to cooperate with you and make more experiments.

**Comment by FangGet** [comment]
the paper is "PackNet-SfM: 3D Packing for Self-Supervised Monocular Depth Estimation", the same author as your paper. could you give the result you reproduced on KITTI? you can also try to make experiments with packnet-block for better results.

for other things, contact me with email: fangasfrank at gmail dot com
