### ISSUE TITLE
训练结果有提升了吗？

### ISSUE THREAD

**Issue by cudnn** [FangGet/PackNet-SFM-PyTorch#6]
Abs Rel | Sq Rel | RMSE | RMSE(log) | Acc.1 | Acc.2 | Acc.3
-- | -- | -- | -- | -- | -- | --
0.119 | 0.890 | 4.855 | 0.198 | 0.862 | 0.954 | 0.980
这个精度基本相当于monodepth2 的水平。
是不是因为为了适应 RTX2060 8G，降低模型训练参数导致的?
需要设备支持吗？很期待更好的训练预测结果。

**Comment by FangGet** [comment]
嗯，这个结果差不多和ImageNet预训练的MonoDepth2结果差不多，后续有提升，不过不太多，就没更新。精度达不到paper效果可能是某些细节还是没有处理好吧，和模型的复杂度可能关系不大。最近在实验新idea，没多少时间做这个的复现了~~

**Comment by cudnn** [comment]
好可惜！如果需要好点的设备做实验或者资金支持给我说一下。我微信ardupilot4，电话13176502829。

**Comment by FangGet** [comment]
哈哈，暂时不需要的，感谢您的好意。微信可以加一个。
