### ISSUE TITLE
The model can be adapted accordingly to your current version as the authors have released the code.

### ISSUE THREAD

**Issue by rvarun7777** [FangGet/PackNet-SFM-PyTorch#7]
https://github.com/TRI-ML/packnet-sfm

**Comment by FangGet** [comment]
thanks for reminding, I'll do it asap.

**Comment by vicentowang** [comment]
I compared the original with this , so many mistakes in this code. you may need clearly read the paper,i recommend.

**Comment by rvarun7777** [comment]
@vicentowang I mean, first off it's a good job and a very good try from @FangGet to reproduce the paper. Sometimes, it's not easy to implement architecture by just reading the paper. I hope the changes will be incorporated by @FangGet with the inference code. In our work [FisheyeDistancenet](https://github.com/rvarun7777/FisheyeDistanceNet) we were able to achieve superior results with resnet itself. The gain from pack net is minimal though.

**Comment by vicentowang** [comment]
you are right ,but i insist that we should build it  then rebuild. by the way, i read the paper only ,and coding the right architecture network. i just read the paper carefully . nothing big difference.

**Comment by FangGet** [comment]
thanks @rvarun7777 .
thanks for your advice. @vicentowang  I'll take some time to rebuild this project.
